spring:
  datasource:
    url: jdbc:mysql://cdb-eco3wrph.gz.tencentcdb.com:10023/timemachine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: bb3960519
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  logging:
    config: classpath:log4j2.yml
  redis:
    host: 47.107.32.4
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
