spring:
  datasource:
    url: jdbc:mysql://cdb-eco3wrph.gz.tencentcdb.com:10023/timemachine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: bb3960519
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  logging:
    config: classpath:log4j2.yml
  redis:
    host: 47.107.32.4
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mail:
    host: smtp.qq.com
    username: 459287499@qq.com
    password: wttwvrzzfmqrbghj
    properties.mail.smtp.port: 465
    from: 459287499@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

