spring:
  datasource:
    url: jdbc:mysql://cdb-eco3wrph.gz.tencentcdb.com:10023/timemachine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: bb3960519
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    config: classpath:log4j2.yml