spring:
  datasource:
    url: jdbc:mysql://cdb-eco3wrph.gz.tencentcdb.com:10023/timemachine?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: bb3960519
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  logging:
    config: classpath:log4j2.yml
  redis:
    host: 47.107.32.4
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mail:
    host: smtp.qq.com
    username: 1421376431@qq.com
    password: tywxttqxligsggif
    properties.mail.smtp.port: 465
    from: 1421376431@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  minio:
    url: http://192.168.1.21:9001
    accessKey: minio
    secretKey: minio123
alipay:
  appId: 2016101800714184
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4oZ6xGcCpfdfPbpgg64xno9qZumpQKxGMkVG55OSRJxoT6kTlA+S9NQNjckieWqTbAzWN/gi8HWGqacaDIwvGt7NCOnrblpDBpGd/mfspHPJontA+6lIvpqsQJH18iosCrfymOdJIHlZUTvNIjpXE+b6me+dSxeS9VBJTRENXZCreXxBaGgExfg1R/TLXhmbSem5YRfPr+WpN97kSIGoTMyA/XESOGq+RoIoYmwCx0BoEpnpuMN6NRFGXnUDsl7hWXRc6gTZZU7Ls4g9FfmFa6POslf9sjveXLyyctkO7e3c610SHkPwn0GP0Rvk8BX5hA6iWLHqZe8gWH0Xfedx1AgMBAAECggEADG6tneVLCN61cn1S9xyFVtE8vg9Ea2OLCfkbFLZqAbAtXFvxCa7Kb0crlD200BzwbuL3bzlE403jLrNyr4/jkhz6kCIZ9cFcu/1TDs+SjwEo/Yx8H1Bt+lFxwWODo6g8lhCbK6JHG54XWBP848zeHuZmRRWgzP0QWwNXPI4jLrYttmLo5bIFIgpguETEILAzR5TXC7xlPKXfHnyXazDkmUtc8VXq7Eu7b40CNG8AHvVxqeO0i5b9YrBkSJyBL/LUtWYJirN1ghA5cm/zI9ThDCgm0xj6vFOCz5rZzuisVoxtaatp9tth0hT2f0Jt1G2/ctxouKsLjDkwQy43jjvqvQKBgQDfoTQ1gmKBNbvBjC5dZr2GZOuHla3LZflRsHrw7l1MPiepU1bbiUrxfy2JWFU3lJUQvrY0cGWqkR8wc+LGXmMaQqY4ZIw0EY/f76xgwmkyNhyGKkCQxkpONzsd99FOR6BMLnOUgruK1RGYriiZMhgDvBeSQK3rTOYWqiA+WRFpnwKBgQDTW0v2XMwpXs+m/E8+72cD07Um4uFtUj+waF3eI2ViRg0iEffSHw1dd+I5HI4mg2mGRC1GcDegQEMfV0/eBF8otWd1J+z9yIFuPp9X2254Hmflk4Qj6hFuMo0BuMOWppIioZouO92VNGscAvJl5/VCdG8Kfs+0LZ9aRM+1TE/pawKBgQC0lX6Nfz6ATJ3Ti5mdPuvo7PHtSQdQ6oXMW5DLohChEsgAShYnrdRg82wYLsaR3WAKZ5bG/cR7WjkvbUVBHtM0T4HepAM7wLrIAMjYUeWU8HFUPiZpQlaalqscZhQU/G4LVq9qy68aSzisbGbIXtVZnrgCGEzZZ/2da8Ah2NbgzQKBgGZjH9Vk9vJDn8yBBdKzHvBXqrX/yryuz3Oh23c1JnQJA2ux0J/Vsx/IZ6rLDoHRv1jvxg8NZaUX/Gw+W85tx7tsxYWXpdL7QtgpNf/VqRo/gI1SfPz48yCzFGP1IarlXn2wU4R6M8mH7ytOsiZzy/g5d2FaNTxPrZaJJyXopf2pAoGBAMKUMxsxTdDiNlfBIYSNxchl/hm/FV9Yx05Qy3gWnn32hMlz+SRwV3+N2rn1V7x8q1z8KameF7O/cMgG/xm7N+Rb42DNBazWJw/tVNZFkY9cDI71Dz21tsUsYyLOGDjZKuEkgwtAVs6vB1CnBV5RKuMFYvOyrR1Cz/zoXb6umE10
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj9Uq1I+zQt45Do0ouvTzTxu2GNe8JImyev1q02nr5ElZd7uPy2rDY35STH8wio0LKcxnOgf0FN5no0tzrMYRbH5w3SSZPnIF0I9glcwAEZux6/BARtXmcHkWiX2m8HuCWT34uJJJxaqm3JhiUp6hFlPhPY8VxZOzq8VmaeC6R1jI4Yo/EC06Y3BTP5w+QoA33jz6km0ElNu2hLhb31IBJYCzRQ9p00Af5psorvAM/ScID9+tt0BPNN7RX9OVsNf+jMs+Rx4CxICIaRAZNS3IMJ8wjtk9hXN7OLvnIQ8aXJ3rTw0C9bZvMcJsh9GdmveWNnfqUfptFh+0ucCb2frPKQIDAQAB
  notifyUrl: http://localhost:8080/timemachine/vip-user/aliPayReturnUrl/
  returnUrl: http://localhost:8080/timemachine/vip-user/aliPayNo/
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do